name: Go central workflow

on:
  workflow_dispatch:
  push:
    paths:
      - '**.go'
      - 'etc/config.json'
      - 'Dockerfile'
      - 'descriptors/ModuleDescriptor-template.json'
      - '.github/workflows/do-go.yml'
    tags:
      - '[vV][0-9]+.[0-9]+.[0-9]+*'

jobs:
  go:
    uses: folio-org/.github/.github/workflows/go.yml@master
    secrets: inherit
    with:
      docker-label-documentation: 'https://github.com/folio-org/ui-ldp/blob/master/doc/reports.md'

