name: Go lint central workflow

on:
  push:
    branches: ['*']
    paths:
      - '**.go'
      - 'go.*'
      - 'reporting/.errcheck-exclude'
      - '**/.golangci.yml'
      - '**/staticcheck.conf'
      - '.github/workflows/go-lint.yml'
  workflow_dispatch:

jobs:
  go-lint:
    uses: folio-org/.github/.github/workflows/go-lint.yml@v1
    with:
      errcheck-excludes-file: 'reporting/.errcheck-exclude'
      golangci-config-file: 'reporting/.golangci.yml'

