name: Go lint central workflow

on:
  push:
    branches: ['*']
    paths:
      - '**.go'
      - 'go.*'
      - 'src/.errcheck-exclude'
      - 'src/.golangci.yml'
      - '.github/workflows/go-lint.yml'
  workflow_dispatch:

jobs:
  go-lint:
    uses: folio-org/.github/.github/workflows/go-lint.yml@FOLIO-3994-go-lint
    with:
      errcheck-excludes-file: 'src/.errcheck-exclude'
      golangci-config-file: 'src/.golangci.yml'

