# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build-test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
      - 'etc/config.json'
      - 'Dockerfile' # Run this workflow first to ensure tests are passing
      - 'descriptors/ModuleDescriptor-template.json'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Build descriptors
      run: make target/ModuleDescriptor.json

    - name: Build program
      run: make target/mod-reporting

    - name: Test
      run: make test
